import { RecurrenceType } from '../../../domain/enums';
import type { Avatar, Category, Pictogram, RoutineTemplate } from '../../../domain/types';

export const SEED_CATEGORIES: Category[] = [
  {
    id: 'hygiene',
    labelKey: 'category.hygiene',
    label: 'Higiene',
    color: '#4FC3F7',
    iconId: 'droplets',
    sortOrder: 1,
    isSystem: true,
  },
  {
    id: 'food',
    labelKey: 'category.food',
    label: 'Alimentación',
    color: '#FFB74D',
    iconId: 'utensils',
    sortOrder: 2,
    isSystem: true,
  },
  {
    id: 'leisure',
    labelKey: 'category.leisure',
    label: 'Ocio',
    color: '#BA68C8',
    iconId: 'gamepad-2',
    sortOrder: 3,
    isSystem: true,
  },
  {
    id: 'school',
    labelKey: 'category.school',
    label: 'Colegio',
    color: '#64B5F6',
    iconId: 'backpack',
    sortOrder: 4,
    isSystem: true,
  },
  {
    id: 'health',
    labelKey: 'category.health',
    label: 'Salud',
    color: '#EF5350',
    iconId: 'heart-pulse',
    sortOrder: 5,
    isSystem: true,
  },
  {
    id: 'shopping',
    labelKey: 'category.shopping',
    label: 'Compras',
    color: '#81C784',
    iconId: 'shopping-cart',
    sortOrder: 6,
    isSystem: true,
  },
  {
    id: 'calm',
    labelKey: 'category.calm',
    label: 'Calma',
    color: '#9575CD',
    iconId: 'moon',
    sortOrder: 7,
    isSystem: true,
  },
  {
    id: 'home',
    labelKey: 'category.home',
    label: 'Casa',
    color: '#FF8A65',
    iconId: 'home',
    sortOrder: 8,
    isSystem: true,
  },
  {
    id: 'transport',
    labelKey: 'category.transport',
    label: 'Transporte',
    color: '#4DB6AC',
    iconId: 'car',
    sortOrder: 9,
    isSystem: true,
  },
];

/** Offline pictogram catalog v1 — emoji placeholders until ARASAAC assets ship */
export const SEED_PICTOGRAMS: Pictogram[] = [
  { id: 'wake-up', categoryId: 'hygiene', label: 'Despertarse', assetPath: '/pictograms/wake-up.svg', emoji: '☀️', iconId: 'sun', keywords: ['despertar', 'mañana'], sortOrder: 1, isSystem: true },
  { id: 'bathroom', categoryId: 'hygiene', label: 'Ir al baño', assetPath: '/pictograms/bathroom.svg', emoji: '🚽', keywords: ['baño', 'wc'], sortOrder: 2, isSystem: true },
  { id: 'wash-face', categoryId: 'hygiene', label: 'Lavarse la cara', assetPath: '/pictograms/wash-face.svg', emoji: '💧', iconId: 'droplets', keywords: ['higiene', 'cara'], sortOrder: 3, isSystem: true },
  { id: 'dress', categoryId: 'hygiene', label: 'Vestirse', assetPath: '/pictograms/dress.svg', emoji: '👕', keywords: ['ropa'], sortOrder: 4, isSystem: true },
  { id: 'teeth', categoryId: 'hygiene', label: 'Lavarse los dientes', assetPath: '/pictograms/teeth.svg', emoji: '🪥', keywords: ['dientes', 'higiene'], sortOrder: 5, isSystem: true },
  { id: 'shower', categoryId: 'hygiene', label: 'Ducharse', assetPath: '/pictograms/shower.svg', emoji: '🚿', keywords: ['ducha'], sortOrder: 6, isSystem: true },
  { id: 'pajamas', categoryId: 'hygiene', label: 'Ponerse el pijama', assetPath: '/pictograms/pajamas.svg', emoji: '🌙', iconId: 'moon', keywords: ['noche'], sortOrder: 7, isSystem: true },
  { id: 'breakfast', categoryId: 'food', label: 'Desayunar', assetPath: '/pictograms/breakfast.svg', emoji: '🥣', iconId: 'utensils', keywords: ['desayuno'], sortOrder: 8, isSystem: true },
  { id: 'lunch', categoryId: 'food', label: 'Comer', assetPath: '/pictograms/lunch.svg', emoji: '🍽️', keywords: ['comida', 'almuerzo'], sortOrder: 9, isSystem: true },
  { id: 'dinner', categoryId: 'food', label: 'Cenar', assetPath: '/pictograms/dinner.svg', emoji: '🍲', keywords: ['cena'], sortOrder: 10, isSystem: true },
  { id: 'water', categoryId: 'food', label: 'Beber agua', assetPath: '/pictograms/water.svg', emoji: '💧', iconId: 'droplets', keywords: ['agua', 'beber'], sortOrder: 11, isSystem: true },
  { id: 'backpack', categoryId: 'school', label: 'Preparar mochila', assetPath: '/pictograms/backpack.svg', emoji: '🎒', iconId: 'backpack', keywords: ['cole', 'mochila'], sortOrder: 12, isSystem: true },
  { id: 'school', categoryId: 'school', label: 'Ir al colegio', assetPath: '/pictograms/school.svg', emoji: '🏫', keywords: ['colegio', 'escuela'], sortOrder: 13, isSystem: true },
  { id: 'home', categoryId: 'home', label: 'En casa', assetPath: '/pictograms/home.svg', emoji: '🏠', iconId: 'home', keywords: ['casa', 'hogar'], sortOrder: 14, isSystem: true },
  { id: 'coat', categoryId: 'home', label: 'Ponerse el abrigo', assetPath: '/pictograms/coat.svg', emoji: '🧥', keywords: ['salir', 'abrigo'], sortOrder: 15, isSystem: true },
  { id: 'goodbye', categoryId: 'home', label: 'Despedirse', assetPath: '/pictograms/goodbye.svg', emoji: '👋', keywords: ['salir', 'adiós'], sortOrder: 16, isSystem: true },
  { id: 'doctor', categoryId: 'health', label: 'Ir al médico', assetPath: '/pictograms/doctor.svg', emoji: '🩺', iconId: 'heart-pulse', keywords: ['médico', 'salud'], sortOrder: 17, isSystem: true },
  { id: 'pharmacy', categoryId: 'health', label: 'Farmacia', assetPath: '/pictograms/pharmacy.svg', emoji: '💊', keywords: ['farmacia', 'medicina'], sortOrder: 18, isSystem: true },
  { id: 'waiting', categoryId: 'health', label: 'Esperar', assetPath: '/pictograms/waiting.svg', emoji: '⏳', keywords: ['espera'], sortOrder: 19, isSystem: true },
  { id: 'supermarket', categoryId: 'shopping', label: 'Supermercado', assetPath: '/pictograms/supermarket.svg', emoji: '🛒', iconId: 'shopping-cart', keywords: ['compras'], sortOrder: 20, isSystem: true },
  { id: 'cart', categoryId: 'shopping', label: 'Carrito', assetPath: '/pictograms/cart.svg', emoji: '🛍️', keywords: ['compras'], sortOrder: 21, isSystem: true },
  { id: 'car', categoryId: 'transport', label: 'Coche', assetPath: '/pictograms/car.svg', emoji: '🚗', iconId: 'car', keywords: ['coche', 'transporte'], sortOrder: 22, isSystem: true },
  { id: 'bus', categoryId: 'transport', label: 'Autobús', assetPath: '/pictograms/bus.svg', emoji: '🚌', iconId: 'bus', keywords: ['autobús', 'transporte'], sortOrder: 23, isSystem: true },
  { id: 'play', categoryId: 'leisure', label: 'Jugar', assetPath: '/pictograms/play.svg', emoji: '🎮', iconId: 'gamepad-2', keywords: ['juego', 'ocio'], sortOrder: 24, isSystem: true },
  { id: 'rest', categoryId: 'calm', label: 'Descanso', assetPath: '/pictograms/rest.svg', emoji: '🛋️', keywords: ['descanso', 'calma'], sortOrder: 25, isSystem: true },
  { id: 'book', categoryId: 'calm', label: 'Leer un cuento', assetPath: '/pictograms/book.svg', emoji: '📖', keywords: ['cuento', 'leer'], sortOrder: 26, isSystem: true },
  { id: 'sleep', categoryId: 'calm', label: 'Dormir', assetPath: '/pictograms/sleep.svg', emoji: '😴', iconId: 'moon', keywords: ['dormir', 'noche'], sortOrder: 27, isSystem: true },
  { id: 'breathing', categoryId: 'calm', label: 'Respirar', assetPath: '/pictograms/breathing.svg', emoji: '🌬️', keywords: ['calma', 'respirar'], sortOrder: 28, isSystem: true },
  { id: 'music', categoryId: 'calm', label: 'Música suave', assetPath: '/pictograms/music.svg', emoji: '🎵', keywords: ['calma', 'música'], sortOrder: 29, isSystem: true },
];

export const SEED_AVATARS: Avatar[] = [
  { id: 'avatar-boy-1', label: 'Niño 1', assetPath: '/avatars/boy-1.svg', sortOrder: 1 },
  { id: 'avatar-girl-1', label: 'Niña 1', assetPath: '/avatars/girl-1.svg', sortOrder: 2 },
  { id: 'avatar-neutral-1', label: 'Neutral 1', assetPath: '/avatars/neutral-1.svg', sortOrder: 3 },
];

export const SEED_ROUTINE_TEMPLATES: RoutineTemplate[] = [
  {
    id: 'routine-morning',
    name: 'Rutina de mañana',
    description: 'Despertar, higiene, desayuno y preparar el día',
    categoryId: 'hygiene',
    pictogramId: 'wake-up',
    sortOrder: 1,
    isSystem: true,
    suggestedAnchorTimeMinutes: 8 * 60,
    suggestedRecurrenceType: RecurrenceType.Weekdays,
    steps: [
      { title: 'Despertarse', pictogramId: 'wake-up', categoryId: 'hygiene', offsetMinutes: 0, durationMinutes: 5, sortOrder: 1 },
      { title: 'Ir al baño', pictogramId: 'bathroom', categoryId: 'hygiene', offsetMinutes: 5, durationMinutes: 10, sortOrder: 2 },
      { title: 'Lavarse la cara', pictogramId: 'wash-face', categoryId: 'hygiene', offsetMinutes: 15, durationMinutes: 5, sortOrder: 3 },
      { title: 'Vestirse', pictogramId: 'dress', categoryId: 'hygiene', offsetMinutes: 10, durationMinutes: 15, sortOrder: 4 },
      { title: 'Desayunar', pictogramId: 'breakfast', categoryId: 'food', offsetMinutes: 25, durationMinutes: 20, sortOrder: 5 },
      { title: 'Lavarse los dientes', pictogramId: 'teeth', categoryId: 'hygiene', offsetMinutes: 45, durationMinutes: 10, sortOrder: 6 },
      { title: 'Preparar mochila', pictogramId: 'backpack', categoryId: 'school', offsetMinutes: 55, durationMinutes: 10, sortOrder: 7 },
    ],
  },
  {
    id: 'routine-night',
    name: 'Rutina de noche',
    description: 'Cena, higiene y prepararse para dormir',
    categoryId: 'calm',
    pictogramId: 'sleep',
    sortOrder: 2,
    isSystem: true,
    suggestedAnchorTimeMinutes: 20 * 60,
    suggestedRecurrenceType: RecurrenceType.Daily,
    steps: [
      { title: 'Cenar', pictogramId: 'dinner', categoryId: 'food', offsetMinutes: 0, durationMinutes: 30, sortOrder: 1 },
      { title: 'Ducharse', pictogramId: 'shower', categoryId: 'hygiene', offsetMinutes: 35, durationMinutes: 15, sortOrder: 2 },
      { title: 'Ponerse el pijama', pictogramId: 'pajamas', categoryId: 'hygiene', offsetMinutes: 55, durationMinutes: 10, sortOrder: 3 },
      { title: 'Leer un cuento', pictogramId: 'book', categoryId: 'calm', offsetMinutes: 65, durationMinutes: 15, sortOrder: 4 },
      { title: 'Dormir', pictogramId: 'sleep', categoryId: 'calm', offsetMinutes: 80, durationMinutes: 10, sortOrder: 5 },
    ],
  },
  {
    id: 'routine-leave-home',
    name: 'Salir de casa',
    description: 'Mochila, abrigo y despedida antes de salir',
    categoryId: 'home',
    pictogramId: 'coat',
    sortOrder: 3,
    isSystem: true,
    suggestedAnchorTimeMinutes: 8 * 60 + 30,
    suggestedRecurrenceType: RecurrenceType.Weekdays,
    steps: [
      { title: 'Preparar mochila', pictogramId: 'backpack', categoryId: 'school', offsetMinutes: 0, durationMinutes: 10, sortOrder: 1 },
      { title: 'Ponerse el abrigo', pictogramId: 'coat', categoryId: 'home', offsetMinutes: 10, durationMinutes: 5, sortOrder: 2 },
      { title: 'Despedirse', pictogramId: 'goodbye', categoryId: 'home', offsetMinutes: 15, durationMinutes: 5, sortOrder: 3 },
    ],
  },
  {
    id: 'routine-hygiene',
    name: 'Higiene personal',
    description: 'Baño, lavarse la cara y dientes',
    categoryId: 'hygiene',
    pictogramId: 'wash-face',
    sortOrder: 4,
    isSystem: true,
    suggestedAnchorTimeMinutes: 9 * 60,
    suggestedRecurrenceType: RecurrenceType.Daily,
    steps: [
      { title: 'Ir al baño', pictogramId: 'bathroom', categoryId: 'hygiene', offsetMinutes: 0, durationMinutes: 10, sortOrder: 1 },
      { title: 'Lavarse la cara', pictogramId: 'wash-face', categoryId: 'hygiene', offsetMinutes: 10, durationMinutes: 5, sortOrder: 2 },
      { title: 'Lavarse los dientes', pictogramId: 'teeth', categoryId: 'hygiene', offsetMinutes: 15, durationMinutes: 10, sortOrder: 3 },
    ],
  },
  {
    id: 'routine-meal',
    name: 'Comida',
    description: 'Sentarse, comer y recoger',
    categoryId: 'food',
    pictogramId: 'lunch',
    sortOrder: 5,
    isSystem: true,
    suggestedAnchorTimeMinutes: 13 * 60,
    suggestedRecurrenceType: RecurrenceType.Daily,
    steps: [
      { title: 'Sentarse a la mesa', pictogramId: 'lunch', categoryId: 'food', offsetMinutes: 0, durationMinutes: 5, sortOrder: 1 },
      { title: 'Comer', pictogramId: 'lunch', categoryId: 'food', offsetMinutes: 5, durationMinutes: 25, sortOrder: 2 },
      { title: 'Recoger la mesa', pictogramId: 'lunch', categoryId: 'food', offsetMinutes: 30, durationMinutes: 10, sortOrder: 3 },
    ],
  },
  {
    id: 'routine-school',
    name: 'Ir al colegio',
    description: 'Prepararse y camino al cole',
    categoryId: 'school',
    pictogramId: 'school',
    sortOrder: 6,
    isSystem: true,
    suggestedAnchorTimeMinutes: 8 * 60 + 15,
    suggestedRecurrenceType: RecurrenceType.Weekdays,
    steps: [
      { title: 'Preparar mochila', pictogramId: 'backpack', categoryId: 'school', offsetMinutes: 0, durationMinutes: 10, sortOrder: 1 },
      { title: 'Despedirse en casa', pictogramId: 'goodbye', categoryId: 'home', offsetMinutes: 10, durationMinutes: 5, sortOrder: 2 },
      { title: 'Ir al colegio', pictogramId: 'school', categoryId: 'school', offsetMinutes: 15, durationMinutes: 20, sortOrder: 3 },
    ],
  },
  {
    id: 'routine-doctor',
    name: 'Ir al médico',
    description: 'Preparación y visita al centro de salud',
    categoryId: 'health',
    pictogramId: 'doctor',
    sortOrder: 7,
    isSystem: true,
    suggestedAnchorTimeMinutes: 10 * 60,
    suggestedRecurrenceType: RecurrenceType.Once,
    steps: [
      { title: 'Preparar documentos', pictogramId: 'doctor', categoryId: 'health', offsetMinutes: 0, durationMinutes: 10, sortOrder: 1 },
      { title: 'Ir al médico', pictogramId: 'doctor', categoryId: 'health', offsetMinutes: 10, durationMinutes: 20, sortOrder: 2 },
      { title: 'Esperar en la sala', pictogramId: 'waiting', categoryId: 'health', offsetMinutes: 30, durationMinutes: 15, sortOrder: 3 },
      { title: 'Visita médica', pictogramId: 'doctor', categoryId: 'health', offsetMinutes: 45, durationMinutes: 20, sortOrder: 4 },
    ],
  },
  {
    id: 'routine-supermarket',
    name: 'Comprar en supermercado',
    description: 'Lista, compras y volver a casa',
    categoryId: 'shopping',
    pictogramId: 'supermarket',
    sortOrder: 8,
    isSystem: true,
    suggestedAnchorTimeMinutes: 17 * 60,
    suggestedRecurrenceType: RecurrenceType.Once,
    steps: [
      { title: 'Hacer la lista', pictogramId: 'cart', categoryId: 'shopping', offsetMinutes: 0, durationMinutes: 10, sortOrder: 1 },
      { title: 'Ir al supermercado', pictogramId: 'supermarket', categoryId: 'shopping', offsetMinutes: 10, durationMinutes: 15, sortOrder: 2 },
      { title: 'Elegir productos', pictogramId: 'cart', categoryId: 'shopping', offsetMinutes: 25, durationMinutes: 30, sortOrder: 3 },
      { title: 'Pagar y volver', pictogramId: 'supermarket', categoryId: 'shopping', offsetMinutes: 55, durationMinutes: 20, sortOrder: 4 },
    ],
  },
  {
    id: 'routine-calm',
    name: 'Tiempo tranquilo',
    description: 'Respirar, escuchar música y relajarse',
    categoryId: 'calm',
    pictogramId: 'breathing',
    sortOrder: 9,
    isSystem: true,
    suggestedAnchorTimeMinutes: 18 * 60,
    suggestedRecurrenceType: RecurrenceType.Daily,
    steps: [
      { title: 'Buscar un sitio tranquilo', pictogramId: 'breathing', categoryId: 'calm', offsetMinutes: 0, durationMinutes: 5, sortOrder: 1 },
      { title: 'Respirar profundo', pictogramId: 'breathing', categoryId: 'calm', offsetMinutes: 5, durationMinutes: 10, sortOrder: 2 },
      { title: 'Música suave', pictogramId: 'music', categoryId: 'calm', offsetMinutes: 15, durationMinutes: 15, sortOrder: 3 },
      { title: 'Juego tranquilo', pictogramId: 'play', categoryId: 'leisure', offsetMinutes: 30, durationMinutes: 20, sortOrder: 4 },
    ],
  },
];

export const EXAMPLE_RECURRENCE_DAILY = {
  type: RecurrenceType.Daily,
  startDate: '2026-01-01',
} as const;
